export const SEARCH_ENTITIES = 'SEARCH_ENTITIES';
export const SEARCH_ASCYNC_ENTITIES = 'SEARCH_ASCYNC_ENTITIES';
export const IS_LOADING = 'IS_LOADING';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';